config/routes.rb
Rails.application.routes.draw do

  get 'registration/new', to: "registration#new"

  post 'registration/new', to: "registration#check"

  root to: 'static_pages#home'

  get 'static_pages/home', to: 'static_pages#home'

  resources :gossips do
    resources :comments
  end

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :gossip, optional: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user, optional: true
  has_many :comments, dependent: :destroy
  default_scope {order(created_at: :asc)}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :gossips
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :set_gossip, only: [:create, :edit, :update, :destroy]

  before_action :set_comment, only: [:edit, :update, :destroy]

  def new
    @comment = Comment.new
  end

  def create

    @comment = @gossip.comments.create(comment_params)
    redirect_to gossip_path(@gossip)
  end

  def edit
  end

  def update
    @comment.update(comment_params)
    redirect_to gossip_path(@gossip)
  end

  def destroy
    @comment.destroy
    redirect_to gossip_path(@gossip.id)
  end

  private

  def set_gossip
    @gossip = Gossip.find(params[:gossip_id])
  end

  def set_comment
    @comment = @gossip.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:anonymous_commentor, :content)
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

  before_action :set_gossip, only: [:show, :edit, :update, :destroy]


  def index
    @gossip = Gossip.all.order('created_at ASC')
  end

  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.create(gossip_params)
    redirect_to gossip_path(@gossip.id)
  end

  def show

  end

  def edit

  end

  def update
    @gossip.update(gossip_params)
    redirect_to gossip_path(@gossip.id)
  end

  def destroy
    @gossip.destroy
    redirect_to gossips_path
  end

  private

  def set_gossip
    @gossip = Gossip.find(params[:id])
  end

  def gossip_params
    params.require(:gossip).permit(:title, :content, :anonymous_gossiper)
  end
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController


  def home
    if session[:user_id]
      @current_user = User.find(session[:user_id])
    end
  end

  def new

  end

  def check
    @current_user = User.where(email: params[:email], password: params[:password]).first
    if @current_user
     flash[:info] = "Bienvenue #{@current_user.first_name} !"
     session[:current_user_id] = @current_user.id
     puts session[:current_user_id]
     redirect_to root_path

    else
     flash[:info] = "Échec de la connexion"
     session[:user_id] = nil
     redirect_to registration_new_path
    end

  end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    redirect_to user_path(@user.id)
  end

  def show
  end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :password, :email, :age)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/edit.html.erb
<h1>&Eacute;diter le commentaire n°<%= @comment.id %></h1>

<%= form_for ([@gossip, @comment]) do |f| %>
<p>
<%= f.label :content, "Le contenu" %>
<%= f.text_area :content %>
</p>
<p>
<%= f.label :anonymous_commentor, "Ton petit nom" %>
<%= f.text_field :anonymous_commentor %>
</p>
<%= f.submit "Modifier le commentaire" %>
<% end %>

<%= link_to 'Clique pour détruire', [@comment.gossip, @comment], method: :delete %>

app/views/gossips/edit.html.erb
<h1>&Eacute;diter le gossip n°<%= @gossip.id %></h1>

<%= form_for @gossip do |f| %>
<label>Le titre : </label><%= @gossip.title %>
<%= f.label :content, "Le contenu" %>
<%= f.text_area :content %>
<%= f.label :anonymous_gossiper, "Ton petit nom" %>
<%= f.text_field :anonymous_gossiper %>
<%= f.submit "Modifier le gossip" %>
<% end %>

<%= link_to 'Clique pour détruire', @gossip, method: :delete %>

app/views/gossips/index.html.erb
<% if @current_user %>
  <h1>Bienvenue <%= @current_user.first_name %> !</h1>
<% else %>
  <h1>Bienvenue visiteur anonyme !</h1>
  <a href="/registration/new">S'identifier</a>
<% end %>

<table>
  <tbody>
    <thead>
      <tr>
        <td>Numéro du gossip</td>
        <td>Titre du gossip</td>
        <td>Contenu du gossip</td>
        <td>Auteur du contenu</td>
        <td>Nombre de commentaires</td>
        <td>Lien du gossip</td>
      </tr>
    </thead>
  <% Gossip.all.each do |gossip| %>
    <tr>
      <td><%= gossip.id %></td>
      <td><%= gossip.title %></td>
      <td><%= gossip.content %></td>
      <td><%= gossip.anonymous_gossiper %></td>
      <td><%= gossip.comments.count%></td>
      <td><%= link_to 'Voir le gossip', gossip_path(gossip.id) %>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'Créer un nouveau gossip', new_gossip_path %>

app/views/gossips/new.html.erb
<h1>Créer un gossip</h1>

<%= form_for @gossip do |f| %>
<%= f.label :title, "Le titre"%>
<%= f.text_field :title%>
<%= f.label :content, "Le contenu"%>
<%= f.text_area :content %>
<%= f.label :anonymous_gossiper, "Ton petit nom"%>
<%= f.text_field :anonymous_gossiper %>
<%= f.submit "Créer le gossip" %>
<% end %>

app/views/gossips/show.html.erb
<h1> Voici le gossip n°<%= @gossip.id %></h1>

<p> <%= @gossip.title %> </p>
<p> Son contenu : <%= @gossip.content %> </p>
<p> Son auteur : <%= @gossip.anonymous_gossiper %> </p>

<p><%= link_to "Editer le Gossip", edit_gossip_path(@gossip) %></p>

<p><%= link_to "Retour à l'accueil", static_pages_home_path %> </p>


<!-- COMMENTAIRES -->

<h2>Commentaires</h2>
  <% @gossip.comments.each do |comment| %>
    <p>
      <strong>Anonymous Commentor :</strong>
      <%= comment.anonymous_commentor %>
    </p>

    <p>
      <strong>Commentaire :</strong>
      <%= comment.content %>
    </p>

<p><%= link_to "Editer le commentaire", edit_gossip_comment_path(@gossip, comment) %></p>

  <% end %>

<!-- AJOUTER UN COMMENTAIRE -->

<h2> Ajouter un commentaire </h2>
<%= form_for([@gossip, Comment.new ]) do |f| %>
  <p>
    <%= f.label :anonymous_commentor, "Ton petit nom" %><br>
    <%= f.text_field :anonymous_commentor %>
  </p>
  <p>
    <%= f.label :content, "Ton commentaire" %><br>
    <%= f.text_area :content %>
  </p>
  <p>
    <%= f.submit "Publier mon commentaire" %>
  </p>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Accueil", '/' %></li>
        <li><%= link_to "Index des gossips", gossips_path %></li>
        <li><%= link_to "Nouveau gossip", new_gossip_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render "layouts/header" %>
  </head>

  <body>
  <div><%= flash[:info] %></div>
  <%= yield %>

  </body>
</html>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Bienvenue !</h1>
  <h3>
    Ici, tu peux retrouver les moussaillons 🎓
  </h3>
  <%= link_to "Enregistre-toi !", registration_new_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/users/edit.html.erb
<h1>&Eacute;diter ton profil n°<%= @user.id %></h1>

<%= form_for @user do |f| %>
<label>ton profil : </label>
<%= f.label :first_name, "Ton prénom" %>
<%= f.text_field :first_name %>
<%= f.label :last_name, "Nom de famille" %>
<%= f.text_field :last_name %>
<%= f.label :age, "ton age" %>
<%= f.number_field :age %>
<%= f.label :email, "ton email" %>
<%= f.email_field :email %>
<%= f.label :password, "ton mot de passe" %>
<%= f.text_field :password %>
<%= f.submit "Enregistrer les modifications" %>
<% end %>

<%= link_to 'Clique pour détruire ton profil', @user, method: :delete %>

app/views/users/new.html.erb
<h1>Crée ton profil</h1>

<%= form_for @user do |f| %>
<%= f.label :first_name, "Ton prénom"%>
<%= f.text_field :first_name%>
<%= f.label :last_name, "Ton nom de famille"%>
<%= f.text_field :last_name %>
<%= f.label :age, "Ton age"%>
<%= f.number_field :age %>
<%= f.label :email, "Ton email"%>
<%= f.email_field :email %>
<%= f.label :password, "ton mot de passe"%>
<%= f.password_field :password %>
<%= f.submit "Crée ton profil" %>
<% end %>

app/views/users/show.html.erb
<h1>Bienvenue <%= @user.first_name %></h1>

<h4>Que veux faire? </h4>

<p><%= link_to "Voir tous les gossips", gossips_path %></p>

<p><%= link_to "Voir tous les gossips", gossips_path %></p>

<p><%= link_to "Editer profil", edit_user_path %></p>